packages:
- 'capstone'
- 'capstone-*'

catalog:
  react-reconciler: ^0.31.0
  react: 19.1.0-canary-4dff0e62-20241213
  vite: ^6.0.3
  '@types/node': ^22
  '@types/react': ^19.0.1
  '@types/react-reconciler': ^0.28.9
